### ISSUE TITLE
[flawhud] Request to port rayshud's Class Selection customization.

### ISSUE THREAD

**Issue by Silexos** [CriticalFlaw/TF2HUD.Editor#100]
Heya! I was wondering if Flawhud could get some more customization options for the class selection screen. More specifically I was wondering if the Rayshud class selection screens could be ported over to Flawhud in the hud editor. I think the "left" customization in particular would look great with the new design of having the class icons next to the class. As always thanks again for all the hard work you put in!

**Comment by CriticalFlaw** [comment]
Transferred this request to this repo because this would be a customization option that is only offered by the editor.
