### ISSUE TITLE
[flawhud] Request to add back the old Mode Selection.

### ISSUE THREAD

**Issue by TempAccountUser** [CriticalFlaw/TF2HUD.Editor#101]
Hi, I like using your HUD but I personally prefer the mode selection menu on the right hand side, although I don't mind it at the bottom. It's just easier to navigate on the right. However It would still be great if there could be an option to move it back to the right without having to go back to older versions. Thanks.

**Comment by CriticalFlaw** [comment]
Transferred this request to this repo because this would be a customization option that is only offered by the editor.
