### ISSUE TITLE
[BUG] Temp.zip cannot be accessed

### ISSUE THREAD

**Issue by LonelySauce** [CriticalFlaw/TF2HUD.Editor#107]
**Describe the issue**
Whenever I attempt to customize sunsetHUD and then install it, I get the following error message:
`An error occurred while installing sunsethud. Access to the path C:\Users\Sauce\Documents\tf2-hud-editor\temp.zip is denied.`

**Steps to reproduce**
Steps to reproduce the issue:
1. Open the HUD Editor
2. Customize sunset HUD then install it

**Screenshots**
Can't upload for some reason.

**Desktop (please complete the following information):**
 - OS: Windows 10 x64
 - App Version: 2.4 (Latest on Gamebanana)
 - Selected HUD: sunsethud

**Comment by LonelySauce** [comment]
Just so you know, creating a folder of any kind does not fix this issue.
Also, the button used to visit the github (in the editor) doesn't work for some reason. Neither do the Huds.tf, discord, steam, documentation, report an issue, buttons work.

**Comment by CriticalFlaw** [comment]
Does it work if you run the app as administrator?

**Comment by LonelySauce** [comment]
No, nothing I do works.

**Comment by LonelySauce** [comment]
> Does it work if you run the app as administrator?

It would be nice to know if you're working on a fix for this since this makes the program completely unusable for me.

**Comment by CriticalFlaw** [comment]
> It would be nice to know if you're working on a fix for this since this makes the program completely unusable for me.

Right now we're trying to reproduce the error to then find the root cause of the issue. Until then you're just gonna have to wait.

**Comment by CriticalFlaw** [comment]
I have not been able to reproduce any of the issues you've reported nor have I had anyone else report something similar regarding sunset Hud or other HUDs supported by the editor. My advise would be to download the latest version here: https://github.com/CriticalFlaw/TF2HUD.Editor/releases/latest extract the folder into somewhere accessible like Desktop and try again. The only thing that makes sense is that you have limited access to your machine and it's preventing you from using the affected features.

**Comment by LonelySauce** [comment]
My SSD is dying right now so this'll have to wait until I get my new SSD.

**Comment by CriticalFlaw** [comment]
Any update on reproducing this issue?
