### ISSUE TITLE
Notify User if a second HUD is already installed.

### ISSUE THREAD

**Issue by TheLexoPlexx** [CriticalFlaw/TF2HUD.Editor#110]
**Describe the feature you're requesting.**
The Idea is basically to alert the user of the HUD-Editor if another HUD is installed already manually inside the tf/custom-Folder.

**Additional context**
Had this problem with boredHUD and trying to install raysHUD.

**Comment by CriticalFlaw** [comment]
That's a good suggestion. Right now, the editor only checks for huds it supports so it should at least attempt to identify any potential hud directories and warn the user.

**Comment by CriticalFlaw** [comment]
Implemented in 535dcaca49d484b5a37f31bbb723df44fe51e72a and will be released in version 2.5. Cheers.
