### ISSUE TITLE
GUI does not fit on screen

### ISSUE THREAD

**Issue by chonga2520** [CriticalFlaw/TF2HUD.Editor#118]
![image](https://user-images.githubusercontent.com/101266955/169325936-d7cfeb4f-38d3-48ab-9e80-26518decf8a2.png)

hello. i was trying to customize budhud, but my screen wouldnt fit the whole GUI of the editor. my screen resolution is 1366x768. can you please make something like a scrollbar to reach the lower controls?

**Comment by CriticalFlaw** [comment]
Fixed in a3e1eebe07ac9f02bbbefd563c7d3a0edb01ce74. Will be released in version 2.5
