### ISSUE TITLE
Add a way to remove the Friends list from hud

### ISSUE THREAD

**Issue by Odyssey346** [CriticalFlaw/TF2HUD.Editor#121]
**Describe the feature you're requesting.**
Toonhud does not have friends list, and it's so nice when you are streaming. I decided to try out FlawHUD for streaming, but when I enabled streamer mode I saw that the friends list was still there. I was wondering if theres a possibility that you could just completely remove the friends list from the hud here? If toonhud can do it, I guess this program could do it as well.
**Additional context**
None required.

**Comment by CriticalFlaw** [comment]
Implemented in 0ac69053f56e136bf0a500b4def1ee7983af3f05
