### ISSUE TITLE
TF2HUD Editor breaks Flawhud's sidebar

### ISSUE THREAD

**Issue by thejaviertc** [CriticalFlaw/TF2HUD.Editor#126]
If you install Flawhud via TF2HUD Editor, part of the sidebar is misplaced, but if you installed it manually (by downloading the master branch and adding it to tf/custom), it's well placed.

Also if you install flawhud manually and you change any setting with TF2HUD Editor, the sidebar misplaces again.

**Steps to reproduce the issue:**
1. Install flawhud via TF2HUD Editor
2. Open TF2 (sidebar misplaced)
3. Uninstall flawhud.
4. Download master branch of flawhud
5. Add it manually to tf/custom
6. Open TF2 (sidebar well placed)

**Screenshots**

Installed with TF2HUD Editor:
![imagen](https://user-images.githubusercontent.com/45662206/182131051-f5e19e0a-d601-4c3b-b901-6406af21b39e.png)

Installed manually:
![imagen](https://user-images.githubusercontent.com/45662206/182131297-100cc645-5b3e-4290-a30d-321aa4a658d1.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 64 bits
 - App Version: 2.5
 - Selected HUD: flawhud

**Comment by CriticalFlaw** [comment]
Fixed in e9dd0606459e1212dfeade088947c1bfc425ba51
