### ISSUE TITLE
Editor says unsupported HUD was found despite no HUD being there

### ISSUE THREAD

**Issue by XKarmaVEVO** [CriticalFlaw/TF2HUD.Editor#128]
Whenever I try to install a HUD using the editor it says an unsupported HUD was found in my custom folder and it asks me if I want to delete it. Every time I click yes it always ends up deleting some files that are needed to even install any HUD.

EDIT: Nevermind, I just never extracted the files into my custom folder

**Comment by CriticalFlaw** [comment]
User resolved. Closing.
