### ISSUE TITLE
Broken HUD after uninstalling a custom one

### ISSUE THREAD

**Issue by OctoRuslan** [CriticalFlaw/TF2HUD.Editor#131]
I installed the Community Hud Fixes but since I didn`t like it I decided to uninstall the HUD. After I uninstalled it and booted into the game, this is what I saw;
![20220813113750_1](https://user-images.githubusercontent.com/52858394/184472404-40b267b8-71c2-4489-a515-0ec7bf48acf6.jpg)
How do I reset to the default?

**Comment by CriticalFlaw** [comment]
Is your `tf/custom` folder clear of any huds? I'd suggest verifying the game cache because it's possible that some hud files were installed over the base tf2 files, though the editor isn't supposed to do that.

**Comment by OctoRuslan** [comment]
I checked the game's integrity, twice even, but still it doesn't change anything. Also, not sure if it's the source of the problem but I used budhud before uninstalling it and using the community fixes.

**Comment by CriticalFlaw** [comment]
Hey, just giving an update that I have not been able to reproduce this issue. Do you still see it happening after clearing out the `tf/custom` folder and installing another hud?

**Comment by CriticalFlaw** [comment]
Closing due to lack of response. This issue usually happens due to a file conflict. The recommendation is to reset the game files or clear out the tf/custom folder then trying again with the latest editor and schema updates.
