### ISSUE TITLE
Accent color won't change on Zeeshud

### ISSUE THREAD

**Issue by rigtbh** [CriticalFlaw/TF2HUD.Editor#134]
it just wont
or accent color means something else

**Comment by CriticalFlaw** [comment]
Possibly caused by a change in zeeshud. Will take a look.

**Comment by CriticalFlaw** [comment]
Hi. Just did a quick test and it looks like the Accent Color option works as expected. It's the color you see in some parts of the name, most prevalent on the main menu. This option requires a game restart to take effect, so you can try that.

Also make sure you're on the latest version of both the editor and the HUD schema (updated using the dropdown menu on the top right corner of the screen then selection: Check for Updates.

**Editor**
![image](https://user-images.githubusercontent.com/6818236/194620585-0f8af32b-d7ba-4bdb-99fa-fef35e50529e.png)

**In-Game**
![20221007135802_1](https://user-images.githubusercontent.com/6818236/194620641-355ab2b4-a364-4a01-92f5-14eebf2286cc.jpg)

**Comment by rigtbh** [comment]
> 
Both of them are at the latest version. Maybe I am just doing it in the wrong order?
