### ISSUE TITLE
[REQUEST] Add new options for FlawHUD's customization

### ISSUE THREAD

**Issue by Tiagoquix** [CriticalFlaw/TF2HUD.Editor#140]
New features that I would like to see:

1. Be able to toggle between gray and the old black in https://github.com/CriticalFlaw/flawhud/blob/master/resource/scheme/clientscheme_settings.res#L91
2. Be able to hide FlawHUD version in main menu (maybe using visible_minmode so it doesn't hide the "Streamer mode activated" message).
3. Be able to hide the supporters pannel on the stats screen, like we can do with the links on the main menu.
4. Be able to toggle between the new player model positions on the HUD and the old ones when using the centered mode. Since the HUD now uses cornered health and ammo by default, it seems the 3D live player models have also changed their position.
5. Make the editor not save files in %localappdata% (folders CriticalFlaw and TF2HUD.Editor), but instead in the folder of the editor itself (e.g. `Desktop\TF2_Hud_Editor\[files here]`).

**Comment by cooolbros** [comment]
The reason the editor saves files in AppData is so that the settings and added HUDs persist between TF2HUD.Editor versions. This is probably not going to change.

**Comment by CriticalFlaw** [comment]
> 1. Be able to toggle between gray and the old black in: https://github.com/CriticalFlaw/flawhud/blob/master/resource/scheme/clientscheme_settings.res#L91

I think this is too niche of a change. Users can change it at their own discretion.

> 2. Be able to hide FlawHUD version in main menu (maybe using visible_minmode so it doesn't hide the "Streamer mode activated" message).

The label helps both identify the version used for troubleshooting and indicate to the user that it's Streamer Mode when they accidently enable it. I don't see value is removing it.

> 3. Be able to hide the supporters pannel on the stats screen, like we can do with the links on the main menu.

Sure, that can be added.

> 4. Be able to toggle between the new player model positions on the HUD and the old ones when using the centered mode. Since the HUD now uses cornered health and ammo by default, it seems the 3D live player models have also changed their position.

I thought they already did that, but it's possible that it was missed in the schema. I'll double check and add that in if it's missing or incorrect.

> 5. Make the editor not save files in %localappdata% (folders CriticalFlaw and TF2HUD.Editor), but instead in the folder of the editor itself (e.g. Desktop\TF2_Hud_Editor\[files here]).

See cooolbros' response.

**Comment by CriticalFlaw** [comment]
Added the option to hide the supporters panel in 76eb82d42b17e4c9502f2863ca42ec4cc12f9ac1

The player model is positioned correctly whether you select cornered or centered layouts. What you may have been referring to is the model's orientation which may have changed slightly but I do not plan on altering that.

**Centered**
![20221101181400_1](https://user-images.githubusercontent.com/6818236/199352482-e126d39b-b45b-4f64-b418-05e462fde670.jpg)


**Cornerned**
![20221101181408_1](https://user-images.githubusercontent.com/6818236/199352477-aa66ccca-7222-4234-b6ff-27ea4b9628cd.jpg)
