### ISSUE TITLE
Inconsistent bars in Cornered Health & Ammo (FlawHud)

### ISSUE THREAD

**Issue by Metisz** [CriticalFlaw/TF2HUD.Editor#144]
Demoknight's and Sniper's Bows' charge meter is in the middle while other things are at the corner
![image](https://user-images.githubusercontent.com/47070328/200054963-95aa020c-facf-4203-9fc1-ba90e4fbf2e5.png)
![image](https://user-images.githubusercontent.com/47070328/200054992-f4b45256-f3bb-4749-a662-cfb0f36b1793.png)
![image](https://user-images.githubusercontent.com/47070328/200055096-45676cce-a08f-4a54-ab35-028b2b66a562.png)
I'd personally prefer if they were all at the middle (and the same color for the matter; most of them still use the old white instead of TanLight) but that's not for me to decide

**Comment by CriticalFlaw** [comment]
Fixed in https://github.com/CriticalFlaw/TF2HUD.Editor/commit/9d85a52559f11268d86d8d8872a08989b2ad2871
