### ISSUE TITLE
[zeeshud] Latest schema does not update player model position

### ISSUE THREAD

**Issue by Umbrozium** [CriticalFlaw/TF2HUD.Editor#147]
![image](https://user-images.githubusercontent.com/38528831/200879125-7955709e-7508-4a43-86d7-5a404cc18710.png)

**Comment by CriticalFlaw** [comment]
I'm not sure what the issue here is. I've installed zeeshud and tried all three layout types and the player model updated for each one. Are you saying it's stuck in the UT layout despite you trying to change it?

**Comment by Umbrozium** [comment]
> I'm not sure what the issue here is. I've installed zeeshud and tried all three layout types and the player model updated for each one. Are you saying it's stuck in the UT layout despite you trying to change it?

What I'm trying to change is the location of the health value in the corresponding .res file. And it doesn't change no matter what value I input. The .res file I'm trying to edit is inside the UT addon.

**Comment by CriticalFlaw** [comment]
Ah I see. It's because you're using alternate fonts which means the placement of the health is being managed set in `health-ammo_alt_font/player_health.res` under **PlayerStatusHealthValue**. Try changing that and see if that resolves it.

**Comment by Umbrozium** [comment]
> Ah I see. It's because you're using alternate fonts which means the placement of the health is being managed set in `health-ammo_alt_font/player_health.res` under **PlayerStatusHealthValue**. Try changing that and see if that resolves it.

Oh, I haven't tried that but I don't think I saw the value component inside player_health.res of the alt font addon. I'll try it.

**Comment by CriticalFlaw** [comment]
@Umbrozium any luck?

**Comment by CriticalFlaw** [comment]
Closing. Solution is mentioned above.
