### ISSUE TITLE
[Request] Centered charge meters for flawhud

### ISSUE THREAD

**Issue by MuchHigher** [CriticalFlaw/TF2HUD.Editor#148]
The demoman shield charge meter is on the right side of the screen, i want it on the middle of the screen like always

Steps to reproduce the issue:
1.  Use FlawHud and open TF2
2.  Search for lobby
3.  select demoman with shield equipped
4.  there, the charge meter for the shield is on the right side of the screen

**Screenshots**
If applicable, add screenshots of the editor settings used.

**Desktop (please complete the following information):**
 - OS: [Windows 8.1, x64]
 - App Version: [e.g. 2.5]
 - Selected HUD: [flawhud]

**Comment by CriticalFlaw** [comment]
Select the centered HUD layout option in the editor

**Comment by CriticalFlaw** [comment]
Closing. Centered charge meters are available with the centered layout option in the editor.

**Comment by MuchHigher** [comment]
still at the corner, only for demoman shield charge, idk why

**Comment by CriticalFlaw** [comment]
@Metisz You'll need to go through the recent commit history and see where it was changed.

@MuchHigher I'll double check but just to be sure, you receive schema update notifications automatically or do you check for updates manually?

**Comment by MuchHigher** [comment]
> 

both

**Comment by MuchHigher** [comment]
@CriticalFlaw both

**Comment by CriticalFlaw** [comment]
Fixed in https://github.com/CriticalFlaw/TF2HUD.Editor/pull/149. You'll need to update your editor schema AND reinstall flawhud to see the changes.
