### ISSUE TITLE
[BUG] Changes to HUD won't go away after uninstall

### ISSUE THREAD

**Issue by XhepYourself** [CriticalFlaw/TF2HUD.Editor#152]
Describe the issue
When uninstalling some HUDs the changes that they make don't get reverted on the vanilla default HUD, leading to visual bugs on other HUDs like some elements being pure white or text not properly showing up on buttons which can make some parts of the games menus practically unusable.

Steps to reproduce the issue:
1. Install Improved Default HUD
2. Open the game, then quit after it loads
3. Uninstall Improved Default HUD
(This applies to other HUDs as well but Improved Default is the most obvious to notice)

You'll notice that the repositioned HUD elements from Improved Default are still applied even though the HUD was uninstalled.

Desktop
 - OS: Windows 11 x64
 - App Version: Latest
 - Selected HUD: None

**Comment by CriticalFlaw** [comment]
What do you see in your `tf/custom` folder after you uninstall the HUD in the editor?

**Comment by CriticalFlaw** [comment]
Closing due to lack of response. Please reopen this issue if there's an update.
