### ISSUE TITLE
[REQUEST] Custom Installation directory

### ISSUE THREAD

**Issue by FolfyBlue** [CriticalFlaw/TF2HUD.Editor#153]
**Describe the feature you're suggesting.**
Hey, due to the very convoluted way I have my system installed, I have two tf2 installations, would it be possible for me to select which installation/directory I want to install an HUD in?

**Additional information**
N/A

**Comment by CriticalFlaw** [comment]
This is already a feature in the current release (2.5), though it's a bit hard to find which we'll correct in the 2.6 release.
![image](https://user-images.githubusercontent.com/6818236/207201823-06d0cdb7-c533-43a4-b46a-591f2d02eed5.png)

**Comment by CriticalFlaw** [comment]
Closing. The feature is already available in the current release.
