### ISSUE TITLE
[BUG] Unable to launch app with new update to .NET 6.0.12

### ISSUE THREAD

**Issue by yslupdates** [CriticalFlaw/TF2HUD.Editor#154]
**Describe the issue**
After I updated .NET to 6.0.12 via windows update, I am no longer able to run the app.

**Steps to reproduce**
Steps to reproduce the issue:
1. Be on .NET 6.0.12
2. Try to run TF2HUD.Editor.exe as admin
3. Get screenshot error below
I ran as admin because I couldn't get any error when the app didn't launch if I double clicked.

**Screenshots**
![image](https://user-images.githubusercontent.com/53108354/207521268-c91bee74-ddd9-4b49-9c95-c3718dee463d.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - App Version: 2.5
 - Selected HUD: flawhud

**Comment by yslupdates** [comment]
To add, I was able to get it working fine with .NET Version 7.0.1 that came out same day as the other one.

All good for now

**Comment by CriticalFlaw** [comment]
Good stuff. I guess they may have made the runtime backwards compatible with .Net 6.

May be worth updating the README to point to downloading .net 7 since we'll probably be moving to it in the next release.
