### ISSUE TITLE
[BUG] 2.5 version of the hud editor says i need NET 6.0 even though I have that and 7.0

### ISSUE THREAD

**Issue by Door09** [CriticalFlaw/TF2HUD.Editor#155]
**Describe the issue**
When I open the hud editor it says I need NET 6.0, I even made sure to install the exact version and 7.0 because I saw someone say using that would fix the problem but it still aint working

**Steps to reproduce**
Steps to reproduce the issue:
1. Run the 2.5 version of the hud editor with the 6.0 core version

**Screenshots**
Proof I have 6.0 core: https://gyazo.com/315da46ef2025c15337058930f75a00a
Proof I have 7.0: https://gyazo.com/e8b32995804ef544425e32764145172b
Proof of error: https://gyazo.com/dd9fb46003f7b7712b6bf224b7d9f65b

**Desktop (please complete the following information):**
 - OS: Windows 10, 64x
 - App Version: 2.5 the 64x version
 - Selected HUD: I cant even get into the app

**Comment by cooolbros** [comment]
The screenshot of 6.0 says you have the ASP.NET Core 6.0. Shared Framework. I dont think this is correct

To run the editor you need the .NET 6.0 Runtime for **Desktop Apps**, either from:
https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.12-windows-x64-installer (x64)
https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.12-windows-x86-installer (x86)

Try installing the desktop runtime relevant to your computer or both and try running again

**Comment by CriticalFlaw** [comment]
@Door09 please try the suggested workaround above and let us know if that resolved your issue. Cheers.

**Comment by Door09** [comment]
worked ty
