### ISSUE TITLE
[BUG] Conflicting hud doesn't allow me to install new huds and deletes internal files.

### ISSUE THREAD

**Issue by ItsFireStorm** [CriticalFlaw/TF2HUD.Editor#159]
Issue:
I'm trying to install any hud and it comes with the issue "Access to the path 'D3D_Compiler_47_cor3.dll' is denied. After that it deletes files and the application doesn't run until I extract them from the .zip.

Version:
HUD-Editor 2.5
Windows 10 22H2 (x64)
![image](https://user-images.githubusercontent.com/38797905/214705234-5da065bd-df1e-4404-bf78-c8234f83b2a1.png)

**Comment by CriticalFlaw** [comment]
Sounds like an AV issue where it deletes some of the editor files. Check if there's anything in your AV that would indicate that.

**Comment by ItsFireStorm** [comment]
AFAIK there's no issue with my AV that directly refers to the location of the files, it may be something else.

**Comment by ItsFireStorm** [comment]
UPDATE: Removing everything on the custom folder did not work, it seems to be an app problem.

**Comment by CriticalFlaw** [comment]
Could you please delete the currently installed version, download the latest (3.0) from here: https://github.com/CriticalFlaw/TF2HUD.Editor/releases/tag/3.0 then try again,

**Comment by cooolbros** [comment]
Can you try the fix at https://www.criticalflaw.ca/TF2HUD.Editor/troubleshoot#access-to-the-path--dll-is-denied ?

**Comment by CriticalFlaw** [comment]
@ItsFireStorm let us know if using the latest version resolves this issue for you. We have not heard a similar issue be reported so if we don't hear back from you, we'll close this ticket.

**Comment by ItsFireStorm** [comment]
After installing the latest version everything works fine, thanks for the fixes.
