### ISSUE TITLE
[BUG] Version 3.0 of hud editor constantly asks for version upgrade from 2.5 to 3.0

### ISSUE THREAD

**Issue by szero** [CriticalFlaw/TF2HUD.Editor#168]
**Describe the issue**
Newest editor version of 3.0 thinks it still on 2.5 version despite removing all the registry and AppData related files.

**Steps to reproduce**
Steps to reproduce the issue:
1. Remove v2.5 program folder.
2. Remove all related registry and AppData/Local entries of it.
3. Every time you open hud editor now you are greeted with the popup below.

PS.  I've noticed that new program makes an AppData/Local Entry with folder named `2.5.0.0`. Maybe just some version variable in the code wasn't updated?

**Screenshots**
![image](https://user-images.githubusercontent.com/15748979/220888842-a9e6859e-2df9-4d4f-a4cd-9fcbd9fe45bd.png)
![image](https://user-images.githubusercontent.com/15748979/220889845-b5b0e533-8b68-4285-a8f6-1a17f285ac8a.png)

**Desktop (please complete the following information):**
 - OS: Win 10
 - App Version: 3.0

**Comment by cooolbros** [comment]
This is likely caused by the <AssemblyVersion>still being 2.5 in the .csproj file

**Comment by CriticalFlaw** [comment]
Fixed in 736cff06dbac78232ba9726a1528de86a5d56ec7 and uploaded the fixed build to the release page.

Also added a note to the release page for any affected users. Please re-test and let me know.

**Comment by szero** [comment]
Nice, the popup is now gone, yeee-haw, makin' bacon, spot on, good on ya!
