### ISSUE TITLE
[BUG] An error occurred while installing (hud). Response status code does not indicate success: 404 (Not Found).

### ISSUE THREAD

**Issue by RoseTheFoxGit** [CriticalFlaw/TF2HUD.Editor#169]
**Describe the issue**
Upon trying to install hud-fixes; it will pop up with a 404 error saying that the hud is not found. This happens in both the x64 and x86 version.

**Steps to reproduce**
Steps to reproduce the issue:
1. Go to 'hud-fixes'
2. Click on 'install'
3. See error

**Screenshots**
https://i.imgur.com/pWOvT9L.png

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro x64
 - App Version: 3.0
 - Selected HUD: hud-fixes

**Comment by CriticalFlaw** [comment]
Fixed in 01db7895c337ce4e9d7803dcef462d9954bb121d. You should receive a notification for a schema update.
