### ISSUE TITLE
An error occurred while installing <hud>. The 'file' scheme is not supported.

### ISSUE THREAD

**Issue by PuzzlePuddles** [CriticalFlaw/TF2HUD.Editor#174]
upon installing an imported custom hud in my case solarlight's hud, it gives me this message back.
"An error occurred while installing SolarLightHUD-master. The 'file' scheme is not supported."

**recreating the issue:**
1. download the hud
2. move the hud to an inner folder inside the custom folder (so "tf/custom/[folder]" in my case)
3. import and install it inside the hud editor

**other rigorous info:**
 - OS: windows 10, x64
 - App Version: 3.0
 - Selected HUD: SolarLightHUD

**Comment by CriticalFlaw** [comment]
Fixed in afd5d86d6b7717103166270206c90bd2f2e819d7 and included in the 3.1 release.
