### ISSUE TITLE
[BUG] AutoUpdater doesn't overwrite old version of the app.

### ISSUE THREAD

**Issue by szero** [CriticalFlaw/TF2HUD.Editor#176]
**Describe the issue**
Hey this is the issue guy again. When new version is detected by the updater, it gets downloaded to separate `tf2-hud-editor` directory instead of being extracted over already existing files so the path after update looks like this: `..\tf2-hud-editor\tf2-hud-editor` and obviously after program restart we are continuously asked to update. Removing outer tf2-hud dir contents and replacing it with stuff that's in the inner folder concludes the update.

**Desktop (please complete the following information):**
 - OS: Win 10
 - App Version: any

**Comment by CriticalFlaw** [comment]
That sounds like the issue with the AutoUpdater dependency that the editor is using. I thought I had disabled the option to download from that pop-up and only allow the user to navigate to the release page. Will need to double check that...

Possibly find a better way of upgrading the editor as well.

**Comment by CriticalFlaw** [comment]
Started replacing AutoUpdaterNET for a manual method where we'll just check the current app version and compare it to the latest release tag on GitHub. Should be simpler and less error prone. 0d8b420ec979cc7f2de3c69928565327378a8efe

**Comment by CriticalFlaw** [comment]
Fixed in f53da8e8220de8cdabf1533c087631d059b34153. This will be included in the next release. Thank you for reporting.
