### ISSUE TITLE
TF2HUD.Fixes schema is outdated.

### ISSUE THREAD

**Issue by RoseTheFoxGit** [CriticalFlaw/TF2HUD.Editor#180]
**Describe the issue**
It seems like the hud editor is applying an older version of tf2 hud fixes, and is not up to date with all the current ongoing changes of tf2 hud fixes (the mp_tournament mode is still in the match hud, for example)

**Desktop (please complete the following information):**
   - OS: Windows 10, x64
 - App Version: 3.1
 - Selected HUD: tf2 hud fixes

**Comment by RoseTheFoxGit** [comment]
It's also come to my attention that some of the "extras" explained and listed inside of the tf2 hud fixes github, aren't available to select on the tf2 hud editor, unless that's intentional?

**Comment by CriticalFlaw** [comment]
Updated the branch for the HUD and the schema file. The only mistake I could find is that the color settings for the crosshair and hitmarker were not pointing to the correct file. Should be good now. Thanks!
