### ISSUE TITLE
[flawhud] Centered MvM money counter

### ISSUE THREAD

**Issue by Presto06** [CriticalFlaw/TF2HUD.Editor#184]
![image](https://user-images.githubusercontent.com/123919000/230729147-bfec8550-8834-4cff-8114-d50738336c4b.png)

Would be cool to see an option for centered mvm money like toonhud (imaged above)

So something like somewhere below your crosshair and above the charge bars and metal count (in centered mode) there will be an counter showing you how much money is left on the floor in a round

This would be ideal for people who main scout in MVM as they can easily see how much money they have left to collect rather than looking at the bottom of the screen constantly

This may be too distracting for most people especially people who dont play scout in MVM so I dont think it should be a part of the main hud but at least an option in the hud editor

**Comment by CriticalFlaw** [comment]
Added in 773375b35239cd7f1e794e87df2c31ec71e80849.
![20230426215242_1](https://user-images.githubusercontent.com/6818236/234740159-0bd8d59c-dcb7-4daa-9fd6-4a50a8a5f1f7.jpg)
