### ISSUE TITLE
[flawhud] Missing sandvich reload indicator

### ISSUE THREAD

**Issue by yslupdates** [CriticalFlaw/TF2HUD.Editor#186]
**Describe the issue**
Heavy sandvich reload meter doesn't show in 2560x1440 display flawhud

**Steps to reproduce**
Steps to reproduce the issue:
1. install latest flawhud as of today
2. play heavy and throw sandvich out or eat
3. look for meter and don't see

**Screenshots**
![20230408212258_1](https://user-images.githubusercontent.com/53108354/230754365-bd237314-e2be-4860-9212-41f0d2f03a5a.jpg)
flawhud settings via tf2hudeditor:
![image](https://user-images.githubusercontent.com/53108354/230754378-7072fc7b-71b5-4fe8-ba4a-fda43c9765a0.png)

**Desktop (please complete the following information):**
 - OS: Windows 11 latest
 - App Version: latest flawhud as of today
 - Selected HUD: flawhud

Edit: it seems to be fine at a later play, unable to reproduce now

**Comment by CriticalFlaw** [comment]
I was able to reproduce the issue by doing other unrelated changes. A game restart fixed it which leads me to believe it's a game bug.
I've also retested with the editor settings specified but the meter remained.
![20230426221105_1](https://user-images.githubusercontent.com/6818236/234742173-453ef438-b1ff-4076-9bde-35affff6fe78.jpg)
