### ISSUE TITLE
[REQUEST] [hud-fixes] Outlined TF2 Build damage numbers

### ISSUE THREAD

**Issue by Presto06** [CriticalFlaw/TF2HUD.Editor#187]
**Describe the feature you're suggesting.**
You can currently switch from normal damage numbers to TF2 Build (larger font) damage numbers however it would be nice if there was an option to have these damage numbers along with an outline because sometimes they can be hard to see

**Additional information**
Add any additional details about your suggestion here.

**Comment by CriticalFlaw** [comment]
This is already implemented under the Damage Value section as "Use Larger Font" - I can see that being misleading.

That customization has now been renamed to "Use TF2 Build Font"

![image](https://user-images.githubusercontent.com/6818236/234749071-f403a666-f5b5-4c56-84d0-1404f3192394.png)
