### ISSUE TITLE
[FLAWHUD] Certain Customizations in wrong section

### ISSUE THREAD

**Issue by Presto06** [CriticalFlaw/TF2HUD.Editor#189]
![image](https://user-images.githubusercontent.com/123919000/235381317-a8160ddf-d944-4583-aa7c-94fd0a8397c9.png)

Alternate damage numbers and Centered MVM money options are under the wrong subsection, they are under main menu when they should be under "Customizations"

**Comment by CriticalFlaw** [comment]
Corrected in https://github.com/CriticalFlaw/TF2HUD.Editor/commit/93d46ed788a3ee9f788e37ef2e9558a8e9e6ee7e. Thanks.

![image](https://user-images.githubusercontent.com/6818236/236081083-9e33ae77-f23a-4148-80d0-ad46b1b08898.png)
