### ISSUE TITLE
[BUG] Install button is disabled when used while TF2 is running.

### ISSUE THREAD

**Issue by Presto06** [CriticalFlaw/TF2HUD.Editor#190]
**Describe the issue**
When trying to install huds while TF2 is open, any further installs are blocked off until you restart the Hud Editor, even if any 

**Steps to reproduce**
Try and install a Hud through the editor with TF2 open,
All further install buttons are greyed out even if TF2 is closed

**Video **

https://user-images.githubusercontent.com/123919000/236350266-79311728-8014-49e9-aae0-471680b338f8.mp4

**Desktop (please complete the following information):**
 - OS: Windows 11
 - App Version: 3.1
 - Selected HUD: All

**Comment by cooolbros** [comment]
Thanks for reporting this issue, it should be fixed by 2eab19c8df23b06bcca1d10641653f77c1993747

**Comment by CriticalFlaw** [comment]
Thanks @cooolbros. I'll test it tonight then close this ticket. This will be included in the next release.

**Comment by CriticalFlaw** [comment]
Tested the fix. Looks good. Thanks!
