### ISSUE TITLE
[flawhud] Small damage number customization does not work

### ISSUE THREAD

**Issue by Presto06** [CriticalFlaw/TF2HUD.Editor#191]
The customization for small damage numbers no longer works on both TF2 fonts and CodePro Fonts

**Comment by CriticalFlaw** [comment]
Fixed in ab894ff51d6f21c935a07e66c695ae6f665aa4be. You should receive a notification for a schema change and you may need to reinstall the hud from the editor before reapplying the customization. Thanks!
