### ISSUE TITLE
[flawhud] Mixed customizations remove health box.

### ISSUE THREAD

**Issue by Presto06** [CriticalFlaw/TF2HUD.Editor#192]
![image](https://user-images.githubusercontent.com/123919000/236377793-90df2642-4a6f-40b2-a20b-bf3b65db90b5.png)

Using "Colored Text" health style along with Cornered HP & Ammo removes the black box behind HP

When using this combination of customizations through the HUD Editor the black box behind the HP which is usually present on cornered mode is gone which makes the hp values look kind of bad with the 3d player model and I doubt this is intentional

**Comment by CriticalFlaw** [comment]
Fixed in 5263f62581725dfe5d5d57741cda4283be8c7241. You should receive a notification for a schema change and you may need to reinstall the hud from the editor before reapplying the customization. Thanks!
