### ISSUE TITLE
Numbers above HP still overlap in some instances on centered mode

### ISSUE THREAD

**Issue by Presto06** [CriticalFlaw/TF2HUD.Editor#193]
![image](https://user-images.githubusercontent.com/123919000/236652159-c23f5a3e-db99-400a-8a75-a85bdced2b6f.png)
![image](https://user-images.githubusercontent.com/123919000/236652079-7b7860fc-9495-4303-8202-960b050731fb.png)

I opened a ticket while ago about this issue and it got somewhat fixed especially with the concheror however large numbers still overlap with eachother (black box and kunai pictured above)

**Comment by CriticalFlaw** [comment]
Fixed in bd21c8bd7b354adc091e253160dfc14e5c6f3fde. You should receive a notification for a schema change and you may need to reinstall the hud from the editor before reapplying the customization. Thanks!
