### ISSUE TITLE
[REQUEST] Weapon specific crosshairs?

### ISSUE THREAD

**Issue by Presto06** [CriticalFlaw/TF2HUD.Editor#197]
Maybe a way for weapon specific crosshairs like on Mastercomfig

**Comment by CriticalFlaw** [comment]
I'm not familiar with how it works in mastercomfig. Can you send a link?

**Comment by Presto06** [comment]
https://mastercomfig.com/app/

You have to edit any preset then there will be 3 boxes you can click on, Modules, Binds and Weapons

Click on weapons and you can choose a class and customize all their weapons with different crosshairs

**Comment by CriticalFlaw** [comment]
Sounds like it's better suited to be left with mastercomfig rather than try to duplicate it in the editor.

The transparent viewmodels are an exception to the rule because that requires HUD changes that mastercomfig does not do.

**Comment by Presto06** [comment]
> Sounds like it's better suited to be left with mastercomfig rather than try to duplicate it in the editor.
> 
> The transparent viewmodels are an exception to the rule because that requires HUD changes that mastercomfig does not do.

https://www.teamfortress.tv/30866/guide-weapon-specific-custom-crosshairs

I actually managed to find a guide from cfg.tf if you wish looking into it, it doesnt appear to be mastercomfig exclusive but yeah if this stuff wont work well with the hud editor then feel free to close this ticket
