### ISSUE TITLE
flawhud.json --- different values (editor / hud itself)

### ISSUE THREAD

**Issue by Tiagoquix** [CriticalFlaw/TF2HUD.Editor#198]
https://github.com/CriticalFlaw/TF2HUD.Editor/blob/master/src/TF2HUD.Editor/JSON/flawhud.json#L622

https://github.com/CriticalFlaw/flawhud/blob/master/resource/ui/scoreboard.res#L455

For both `BluePlayerList` and `RedPlayerList`, the value is `210` in the editor (when false) but `204` in the HUD itself.

**Comment by CriticalFlaw** [comment]
Corrected in 2b81fb301336b974afb6419776f3788106313f03. Thanks.
