### ISSUE TITLE
[flawhud] Suggested changes to the Centered MVM Currency option

### ISSUE THREAD

**Issue by Presto06** [CriticalFlaw/TF2HUD.Editor#199]
Here are some suggested changes for the recently added "Cantered MVM Currency" option in the Hud Editor

First of all:

![image](https://github.com/CriticalFlaw/flawhud/assets/123919000/1c4470e3-3def-4de0-85ee-601afdedadb4)

The canteen icon next to the cash looks kinda awkward with this option enabled it looks a bit too "heavy" on one side, since the remaining currency option is moved somewhere else if you get what im saying

Perhaps make the canteen smaller so it fits nice next to the cash so something like this (ignore scuffed editing): 

![image](https://github.com/CriticalFlaw/flawhud/assets/123919000/c218a185-a473-4d1f-ad07-70251b4136c2)

Or move it to the bottom of the screen

My 2nd suggestion would to be perhaps lower where the remaining currency is because I believe right now its too close to the crosshair and add a outline to the text so it pops out more

**Comment by CriticalFlaw** [comment]
Added in a0c4fd9ae48cfa84f05db0b55ae532711b4e46a7. The canteen counter is now smaller and added a dropshadow the cash counter. I didn't like how it looked lower even more so it will be left as is. Thanks.
