### ISSUE TITLE
[flawhud] Add back the customization to hide the health/ammo box

### ISSUE THREAD

**Issue by MuchHigher** [CriticalFlaw/TF2HUD.Editor#200]
The hud changed, maybe it's because certain fix that fixed the colorized number when cornered mode bug.
it's kinda blocking my view, and it's kinda harder to see the health numbers because it gotten further away from the crosshair.
are there any settings to disable the black box? and maybe revert the distance? i mean yeah i can adapt, but i'll ask anyway
from this:
![20230413070714_1](https://github.com/CriticalFlaw/TF2HUD.Editor/assets/115716636/902f2ff4-f804-400e-89b3-85297f8ac043)
 to this:
![20230615191231_1](https://github.com/CriticalFlaw/TF2HUD.Editor/assets/115716636/62dac07f-6593-4e6a-a38d-e35c77a07c32)
(or the other way around, i don't rember which picture because it entered as a text :))

 - OS: Windows 10, x64
 - App Version: 3.1
 - Selected HUD :FlawHud

**Comment by CriticalFlaw** [comment]
Colored Box option added back to the editor. Thanks.
![20230628234742_1](https://github.com/CriticalFlaw/TF2HUD.Editor/assets/6818236/f6d3e7b9-03f4-4d99-bf6e-5802d407fe6a)
