### ISSUE TITLE
[BUG] Game crashes upon class selection

### ISSUE THREAD

**Issue by PinkPlague** [CriticalFlaw/TF2HUD.Editor#204]
Whenever I install a hud from the editor it causes a crash once I select a class. I can join servers and teams, it only crashes upon choosing a class, any class I must add. works with any settings, default, any combination of settings.

Steps to reproduce the issue:
1. select a hud
2. Click on install
3. once install is complete open tf2 using in-editor tf2 button or through steam library
4. once loaded open a server/ listen server and select a team and class
5. notice crash of game

 - OS: Windows 11, x64
 - App Version: [e.g. 2.6]
 - Selected HUD: any

**Comment by CriticalFlaw** [comment]
Can you post a screenshot of your tf/custom directory please?

**Comment by CriticalFlaw** [comment]
Closing due to lack of response. I'd suggest removing everything from custom folder, verify your game files try without a hud then try with a hud installed via the editor. Thanks
