### ISSUE TITLE
[flawhud] Thermal Thruster is not affected by Item Meter position customization

### ISSUE THREAD

**Issue by Presto06** [CriticalFlaw/TF2HUD.Editor#207]
![image](https://github.com/CriticalFlaw/flawhud/assets/123919000/0e66b551-8623-4246-b392-0f40ed3be57f)

**Comment by CriticalFlaw** [comment]
Fixed in cfd4fbb4d7b53ae01078676e9ceafaddb782ceb5. You should get a notification in the editor to update the schema. Thanks.
