### ISSUE TITLE
[flawhud] Huntsman charge placement on centered

### ISSUE THREAD

**Issue by Presto06** [CriticalFlaw/TF2HUD.Editor#208]
![image](https://github.com/CriticalFlaw/flawhud/assets/123919000/94f08014-aa84-491e-99bd-c23b203e25bb)

The huntsman charge meter is placed directly under the jarate meter which makes it kinda hard to see

Not sure if this is intentional or a bug but ill create a ticket just incase

**Comment by CriticalFlaw** [comment]
Fixed in 89762f382d6344a5e11bad414b142c37e8e1c760. You should get a notification in the editor to update the schema. Thanks.
