### ISSUE TITLE
[hud-fixes] Add option to toggle floating health replacement

### ISSUE THREAD

**Issue by Foxydapirate12** [CriticalFlaw/TF2HUD.Editor#213]
**Is your feature request related to a problem? Please describe.**
Add an option to disable the ally health replacement feature to Hud Editor, or maybe add some config options for the optional content to help players with telling what each optional feature is and what files correspond to them by perhaps making them into a True/False variable in a config file

**Additional context**
![Team Fortress 2 02_08_2023 5_10_28 PM (3)](https://github.com/CriticalFlaw/TF2HUD.Fixes/assets/101042481/dc1590a3-5f30-4ae2-864a-1802f881bae5)

**Comment by CriticalFlaw** [comment]
The floating health customization has been removed in the previous hud-fixes update so this is no longer required.
