### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by SmithAndwessonKnife** [CriticalFlaw/TF2HUD.Editor#215]
**Describe the issue**
A clear and concise description of what the issue is.
hud not using custom backround after hud editor
**Steps to reproduce**
Steps to reproduce the issue:
clicked browse i saw the background i picked 

**Screenshots**
If applicable, add screenshots of the editor settings used.
![Screenshot 2024-01-02 193044](https://github.com/CriticalFlaw/TF2HUD.Editor/assets/155413271/62486823-8870-4f23-9dac-47f591f10073)
![image_2024-01-02_193134382](https://github.com/CriticalFlaw/TF2HUD.Editor/assets/155413271/f7121295-cfab-497e-bce2-03507bebe56e)

**Desktop (please complete the following information):**
 - OS: Win 11
 - App Version: 3.2
 - Selected HUD: Peach Hud

**Comment by SmithAndwessonKnife** [comment]
i even added all the other stuff like title_team_halloween_widescreen as the image but it keeps going back to this one

**Comment by cooolbros** [comment]
It looks like PeachHUD has an extra ImagePanel on the main menu that covers up the default background (resource/ui/mainmenuoverride.res > MountainPanel > Mountain). I'm not sure what the editor could do about this

**Comment by SmithAndwessonKnife** [comment]
oh thank you
