### ISSUE TITLE
[zeeshud] Floating Healthbar Doesn't Always Work

### ISSUE THREAD

**Issue by levinaHR** [CriticalFlaw/TF2HUD.Editor#219]
**DESCRIBE THE ISSUE**
I have a problem with ZeesHUD where the floating healthbar does not work all the time like the default hud or other custom huds. This happened on almost every version of ZeesHUD that I tried: [the main version](https://github.com/Zeesastrous/ZeesHUD), [the original](https://github.com/Zeesastrous/ZeesHUD/tree/original), [the x-beta](https://github.com/Zeesastrous/ZeesHUD/tree/zeeshud-X-beta), and lastly the version I installed using this TF2HUD editor app.

In community servers the floating healthbar doesn't work at all so when I play Spy I don't even know how much health the enemy has unless I disabled the floating healthbar. And when I tried in itemtest map it only works on one of the bot. The weird thing is it does work on casual servers but only when I look at the enemy team as Spy, unfortunately Medic with solemn vow equipped still can't see the enemy healthbar. The floating healthbar for teammates still doesn't work in casual.

And today I just found out that if I look at a player, then press tab to open and close the leaderboards, the floating healthbar works as long as I keep looking at that player. If I break my view then look at them again it won't show the floating healthbar until I press tab again.

**SCREENSHOTS**
Works on one bot,
![Screenshot (367)](https://github.com/CriticalFlaw/TF2HUD.Editor/assets/60391223/86c45e81-8c64-427c-a769-9d917dca4055)

But not on the other bots.
![Screenshot (368)](https://github.com/CriticalFlaw/TF2HUD.Editor/assets/60391223/e4c518b3-3621-4cb6-905e-a9b27a1af0ea)
![Screenshot (369)](https://github.com/CriticalFlaw/TF2HUD.Editor/assets/60391223/75455d8a-f4f4-4856-b27c-1b4761fc1b60)

Looking at a player, no healthbar above head.
![Screenshot (370)](https://github.com/CriticalFlaw/TF2HUD.Editor/assets/60391223/62edf86e-bc05-4947-af2c-5e3da6eef68e)

Press tab to bring the scoreboard,
![Screenshot (371)](https://github.com/CriticalFlaw/TF2HUD.Editor/assets/60391223/3cb4188e-5308-434a-b352-3c7e21ba309b)

and when the scoreboard is closed, the floating healthbar shows up, but will disappear again if I break my view on said player
![Screenshot (372)](https://github.com/CriticalFlaw/TF2HUD.Editor/assets/60391223/06c8c2b5-3d92-496b-b29f-51601d2a31d9)

**DESKTOP**
 - OS: Windows 10
 - App Version: 3.2
 - Selected HUD: ZeesHUD

**Comment by CriticalFlaw** [comment]
Hello. Sorry it took so long to reply back to this. I took a look at this issue and found that it's a problem with zeeshud itself, not the editor. This issue can be replicated with the latest version of zeeshud available on GitHub.

I've tried for a bit to resolve it but wasn't able to. Sorry but I'm going to close this ticket as it's not editor-related.
