### ISSUE TITLE
[hud-fixes] The HP Indicator is stuck and smushed in the top left corner, and there's no HP number.

### ISSUE THREAD

**Issue by xDroflLOL** [CriticalFlaw/TF2HUD.Editor#221]
**Issue**
Title

**Specifications**
Additional information about the issue: Windows 10 21H2, game was running at 1920x1080, all I did was install this hud with these settings.
![image](https://github.com/CriticalFlaw/TF2HUD.Fixes/assets/87008513/d24d40f7-8569-4ebd-8de4-cf37bc2c16ef)

**Screenshots**
![image](https://github.com/CriticalFlaw/TF2HUD.Fixes/assets/87008513/c7b1255f-a1b4-475a-93d8-c500339424f9)

**Comment by CriticalFlaw** [comment]
There have been a few changes to the HUD and schema so the issue should be resolved now. From my testing, it looks good though you'll probably need to reinstall the HUD just in case. Please retest and confirm.

**Comment by CriticalFlaw** [comment]
Closing as the issue has been resolved after testing.
