### ISSUE TITLE
[BUG] while playing mvm the progress bars are messed up like for example the tanks health is both white for the health it has and white for the health it has lost please fix it 

### ISSUE THREAD

**Issue by willywilliam1234** [CriticalFlaw/TF2HUD.Editor#226]
**Describe the issue**
A clear and concise description of what the issue is.

**Steps to reproduce**
Steps to reproduce the issue:

**Screenshots**
If applicable, add screenshots of the editor settings used.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10, x64]
 - App Version: [e.g. 2.6]
 - Selected HUD: [e.g. flawhud]

**Comment by CriticalFlaw** [comment]
Which HUD is this an issue with?

**Comment by willywilliam1234** [comment]
> Which HUD is this an issue with?

the health bar of the tank in MvM

**Comment by willywilliam1234** [comment]
the health bar of the tank is the problem for me

**Comment by CriticalFlaw** [comment]
I mean which HUD did you install through the editor?

**Comment by willywilliam1234** [comment]
oh sorry zeeshud

**Comment by willywilliam1234** [comment]
sorry just got the editor a day ago..

**Comment by willywilliam1234** [comment]
i found another thing, i cant see my teams hp and me (a heavy main) i normaly heal my team but i dont know if they need it or not

**Comment by CriticalFlaw** [comment]
Hi. This looks to be an issue with zeeshud itself. I don't maintain that hud so I cannot fix the issue via the editor.
