### ISSUE TITLE
[BUG] Theme color issue for FLAWHUD in editor

### ISSUE THREAD

**Issue by wilsonwagonwheel** [CriticalFlaw/TF2HUD.Editor#232]
**Describe the issue**
the theme color changes the background for the ammo text box and the letter colors in the menu at the same time, so i can either have a white background for the ammo text box and health box, or invisible letters on the menu. 

**Steps to reproduce**
Steps to reproduce the issue:
1. open tf2 hud editor on flawhud 
2. literally dont even change anything
3. open tf2
4. the ammo box and health box colors are messed up

**Screenshots**
![20240724203557_1](https://github.com/user-attachments/assets/2ba4c50b-ab2c-44c1-9112-e77f25154884)

**Desktop (please complete the following information):**
 - OS: Windows 10, x64
 - App Version: 3.2 hud editor
 - Selected HUD: flawhud

**Comment by CriticalFlaw** [comment]
Reinstall the HUD from within the editor

**Comment by wilsonwagonwheel** [comment]
> Reinstall the HUD from within the editor

thank you, my issue has been fixed

**Comment by CriticalFlaw** [comment]
> > Reinstall the HUD from within the editor
> 
> 
> 
> thank you, my issue has been fixed

No problem
