### ISSUE TITLE
[BUG] [Rayshud] Editor Saves 'hudlayout_base.res' Customizations in the Wrong Directory

### ISSUE THREAD

**Issue by MA113822** [CriticalFlaw/TF2HUD.Editor#233]
**Describe the issue**
Rayshud's hudlayout_base.res is saved in "rayshud/scripts". When attempting to apply customizations that change this file (i.e crosshairs and hitmarkers) it does not edit "rayshud/scripts/hudlayout_base.res", but rather creates a new hudlayout_base.res in "rayshud/resource/ui" with the customizations. This results in those customizations not applying and the user having to manually edit "rayshud/scripts/hudlayout_base.res" to properly apply their customizations. 

**Steps to reproduce**
Steps to reproduce the issue:
1. Select and install Rayshud in the editor. 
2. Edit the crosshair settings. 
4. Click "Apply Changes" 
5. A new hudlayout_base.res should appear in "rayshud/resource/ui" with only the selected changes. 

**Screenshots**
![Screenshot 2024-08-07 151346](https://github.com/user-attachments/assets/48b44105-0ab8-40b0-b41d-5daef688864e)

**Desktop (please complete the following information):**
 - OS: Windows 10 x64
 - App Version: 3.2
 - Selected HUD: Rayshud

**Comment by CriticalFlaw** [comment]
Fixed in b2b3a9c4023af7716de2a5c65af5c9f2a9a29323. Thank you for reporting it.
