### ISSUE TITLE
[zeeshud] Hitmarker changes not working

### ISSUE THREAD

**Issue by GreasyWario27** [CriticalFlaw/TF2HUD.Editor#235]
**Describe the issue**
After changing the hitmarker on the app it didn't change and I had to change things through the huds files.

**Steps to reproduce**
Steps to reproduce the issue:
1. Chnage Hitmarker to anything
2. Boot up TF2 and head into a match
3. When hitting someone it doesn't change

**Screenshots**
No screenshots

**Desktop (please complete the following information):**
 - OS: Windows 11, x64
 - App Version: I'm not sure how to check, but it's the most recent from this post being made.
 - Selected HUD: Zeeshud

**Comment by CriticalFlaw** [comment]
Can you post a screenshot of your editor settings please

**Comment by CriticalFlaw** [comment]
Fixed in d061a49ba9ec67c0d8ea15c014ab2d0b12bf32a7

You should receive a notification to download the latest schema change. The updated zeeshud page should look like this
![image](https://github.com/user-attachments/assets/9bdf499f-ef1f-456b-88a3-bf56f6a9c26d)

With the latest change the crosshair and hitmarker are now separate toggles that you'll need to enable but both have been tested to work. Let me know if it works on your end. Thanks

**Comment by GreasyWario27** [comment]
I did get the update and it works, but I do have another issue, it's not that important but the main menu in the screenshot has a different look for the friends list and placement than the main menu in my game. 
Also, not an issue, but there could be an option to add an outline to the crosshair and hitmarker since you can add it using the customization files.
![TF2 HUD Editor Screenshot](https://github.com/user-attachments/assets/84823e7a-8acf-4ad4-baea-03dabf781e63)
![TF2 Main Menu Screenshot](https://github.com/user-attachments/assets/ff30b87b-3886-459c-a3d9-5ed843ebb2b2)

**Comment by CriticalFlaw** [comment]
> I did get the update and it works, but I do have another issue, it's not that important but the main menu in the screenshot has a different look for the friends list and placement than the main menu in my game. 
> 
> Also, not an issue, but there could be an option to add an outline to the crosshair and hitmarker since you can add it using the customization files.
> 
> ![TF2 HUD Editor Screenshot](https://github.com/user-attachments/assets/84823e7a-8acf-4ad4-baea-03dabf781e63)
> 
> ![TF2 Main Menu Screenshot](https://github.com/user-attachments/assets/ff30b87b-3886-459c-a3d9-5ed843ebb2b2)
> 
> 

I can update the screenshots but adding additional customizations should be up to the author.

**Comment by CriticalFlaw** [comment]
Pushed zeeshud schema with updated screenshots. Thanks
![image](https://github.com/user-attachments/assets/3a4a2c05-2b21-40f3-8544-bf05a4579abc)
