### ISSUE TITLE
[flawhud] Damage number and health style doesn't change, always default.

### ISSUE THREAD

**Issue by tompa71a** [CriticalFlaw/TF2HUD.Editor#237]
As it says in the topic. When changing damage numbers to anything is still is big bold no matter what I set (I like the thin small). Same with the healthstyle, always default settings there too no matter what I choose.
I did redownload and reinstall the app. Also deleted all json files so it was downloaded again. Did not help.

**Comment by CriticalFlaw** [comment]
Can you post a screenshot of your editor and the tf/custom directory please.

**Comment by tompa71a** [comment]
![Skärmbild 2024-08-25 202542](https://github.com/user-attachments/assets/7c7b3a90-9986-47ea-88d8-dd06f2b94046)
![Skärmbild 2024-08-25 202631](https://github.com/user-attachments/assets/08ccd648-4222-46ca-9494-2aa899ce0564)

comfig-custom is just crosshairs. I have tried without it. No difference.

**Comment by tompa71a** [comment]
![Skärmbild 2024-08-25 203346](https://github.com/user-attachments/assets/4f38c87a-bbd5-45d4-8d30-d0419730fea2)

**Comment by CriticalFlaw** [comment]
Thank you. The files appear to be correct. Can you post the logs found on the Editor'a logs folder?

This may be related to stale editor files in AppData, for which several recent issues have been reported and will be addressed in the next release

**Comment by tompa71a** [comment]
[20240831.log](https://github.com/user-attachments/files/16825484/20240831.log)

**Comment by CriticalFlaw** [comment]
Thanks. This is related to #231 which has been reported by multiple users recently. It will be fixed in the future release but in the meantime what some users reported as working for them is going to their AppData directory

`C:\Users\[username]\AppData\Local` and deleting the `CriticalFlaw` folder. This will reset all customizations but should also fix the issue for you.

**Comment by tompa71a** [comment]
Deleted the folder and reinstalled. Did not help. Also tried to delete the folder after install. No change then either.

**Comment by CriticalFlaw** [comment]
Can you please try the preview build https://github.com/CriticalFlaw/TF2HUD.Editor/releases/tag/3.3-preview and see if that resolves the issue?

**Comment by tompa71a** [comment]
Tried 3.3. Still default settings.

**Comment by CriticalFlaw** [comment]
Do you happened to have multiple drives on your PC besides the C drive?

**Comment by tompa71a** [comment]
Yes. I have a D drive I more or less only have torrents on.

mån 2 sep. 2024 kl. 20:39 skrev Igor ***@***.***>:

**Comment by tompa71a** [comment]
I installed net 8.0 and now hudeditor 2.3 will not start, only 3.3 works.

Den tis 3 sep. 2024 kl 16:27 skrev Tom Österström ***@***.***>:

**Comment by tompa71a** [comment]
I found a hudeditor directory under local, deleted it and also deleted the criticalflaw directrory once again.
Now it works! Any settings I try works ingame.

**Comment by CriticalFlaw** [comment]
Thanks. I'll add a clear cache option that will perform this action for the user to resolve this issue. 5564cdc7ee0fae7df95d5d09a6ccdaedd37f2423
