### ISSUE TITLE
[BUG]  cant see vote text

### ISSUE THREAD

**Issue by lucasdaweb95** [CriticalFlaw/TF2HUD.Editor#241]
**Describe the issue**
in community fixes hud, when another player makes a vote the text is broken and shows up as %voteissue%
**Steps to reproduce**
Steps to reproduce the issue:
download community fixes
join server
have a **different** player make a vote
%voteissue%

**Screenshots**
![20240831124434_1](https://github.com/user-attachments/assets/e823f719-f9a1-42cb-9516-25b7f350e3c8)

**Desktop (please complete the following information):**
 - OS: Windows 11, x64
 - App Version: 3.2
 - Selected HUD: community fixes

**Comment by CriticalFlaw** [comment]
This is a known game bug unrelated to the Editor. This is fixed by next vote cycle or when you reload the HUD using the console command `hud_reloadscheme`.
