### ISSUE TITLE
[BUG] App downloaded off GitHub does not launch

### ISSUE THREAD

**Issue by Woopytf** [CriticalFlaw/TF2HUD.Editor#242]
**Describe the issue**
A clear and concise description of what the issue is.

So i open it, works fine and i close it again, doesn't open no matter what i do.

**Steps to reproduce**
Steps to reproduce the issue:
1. Download the 3.2 release
2. Open it
3. Close it
4. try opening it again

**Screenshots**
If applicable, add screenshots of the editor settings used.

**Desktop (please complete the following information):**
 - OS: Windows 11, 64x
 - App Version: 3.2
 - Selected HUD: flawhud

**Comment by szero** [comment]
Yea just happened to me after downloading the schema update and closing the program. Also the prompt with the update asks you if you want to restart now but after accepting nothing happens. If I recall correctly it was like that for few schema updates before but program was working fine after restarting.

**Comment by CriticalFlaw** [comment]
Does deleting the JSON folder then starting the program again solve the issue?

I may need to update the 3.2 release to have the latest JSON files because that seems to cause a lot of issues lately.

**Comment by szero** [comment]
Nope, doing either one or both at the same time doesn't make it work again, no error log is created and only thing I notice is that it makes an empty folder again in that AppData directory.

**Comment by CriticalFlaw** [comment]
I've added a clear cache option for the next release that will perform the clean-up for you. 5564cdc7ee0fae7df95d5d09a6ccdaedd37f2423

In the meantime, try downloading [JSON.zip](https://github.com/user-attachments/files/16935357/JSON.zip) and extract it into your HUD Editor directory. I found that if the JSON folder and certain files are missing it fails to boot.

**Comment by ar1a** [comment]
same as @szero

**Comment by CriticalFlaw** [comment]
Could you please try the new 3.3 RC2 release: https://github.com/CriticalFlaw/TF2HUD.Editor/releases/tag/3.3-rc2

There have been so many changes since release of 3.2 that I don't think it's longer viable for public use given all the schema changes that came since.

**Comment by ar1a** [comment]
that worked great!

**Comment by szero** [comment]
Yep, this one worked great, could be just made into official one since the 3.2 is defunct?

**Comment by CriticalFlaw** [comment]
Yes, it will be promoted to official in the next day or so. I'm waiting for some feedback on it from few other users in case there's an issue. I'll close this ticket once the release is made. If you experience any major issues please let me know. Thanks!

**Comment by CriticalFlaw** [comment]
The full release is now available - https://github.com/CriticalFlaw/TF2HUD.Editor/releases/latest

Thank you everyone for testing the pre-release!
