### ISSUE TITLE
[FLAWHUD] Remove redundant "Default Chat Font" customization

### ISSUE THREAD

**Issue by Presto06** [CriticalFlaw/TF2HUD.Editor#249]
Due to Flawhud no longer using a custom font for text chat, this customization is no longer needed

![image](https://github.com/user-attachments/assets/8b7d8364-1a2b-4c2e-812d-c51c25a07f2d)

**Comment by CriticalFlaw** [comment]
Removed in 437372e3d416b5c8a9f450317c9cdd57989c8690. Thanks
