### ISSUE TITLE
[BUG] Window scaling with Windows messed up past 100%

### ISSUE THREAD

**Issue by sparaan** [CriticalFlaw/TF2HUD.Editor#258]
**Describe the issue**
~~Cannot resize the window, i.e. the mouse doesn't turn into the resizing mode to resize the window.~~ 
(have to use the lower right corner to resize (intended))
I maximized and moved the window by right clicking the preview while hovering the icon on the taskbar.
Maximizing it covers the taskbar as well.

Update:
Scaling is messed up past 100% in Windows.

**Steps to reproduce**
Steps to reproduce the issue:
1. Open the .exe.

**Screenshots**
![SAMj0pyp7I](https://github.com/user-attachments/assets/1860dc5c-83f2-4764-8c1f-46d0ac2bba4d)

**Desktop (please complete the following information):**
 - OS: Win11
 - App Version: 3.4
 - Selected HUD: N/A

**Comment by CriticalFlaw** [comment]
Resizing has already been added back
https://github.com/CriticalFlaw/TF2HUD.Editor/issues/250

Maybe increase your screen resolution

**Comment by CriticalFlaw** [comment]
I've added all-side resizing in https://github.com/CriticalFlaw/TF2HUD.Editor/commit/6646fb2635f681066955ab6bf33ab87849904528 which should help address the issue.

Nothing much I can do about it when you scale up your resolution though. Here's how the app looks maximized on my monitor (3440x1440)
![image](https://github.com/user-attachments/assets/21b62bb7-cd47-4af3-aba7-e2f895d90bdc)

**Comment by CriticalFlaw** [comment]
Try this release and see if it works better: https://github.com/CriticalFlaw/TF2HUD.Editor/releases/tag/3.4.1

**Comment by sparaan** [comment]
> Try this release and see if it works better: https://github.com/CriticalFlaw/TF2HUD.Editor/releases/tag/3.4.1
Resizing from any side works, the title bar snaps back into view if its outside of view, making it able to maximize without using workarounds. 
Just that question on maximize being windowed full screen, covering the taskbar, other than that this is fine to be closed.
