### ISSUE TITLE
[flawhud] Centered Vaccinator Icon doesn't apply and has wrong description

### ISSUE THREAD

**Issue by Meladoom** [CriticalFlaw/TF2HUD.Editor#263]
![image](https://github.com/user-attachments/assets/6d6a56cc-1b1a-4fdd-ba36-a3aec7c5b273)
![image](https://github.com/user-attachments/assets/609ec6e3-06e3-471e-913a-51138799f633)

![image](https://github.com/user-attachments/assets/1d44f8e8-53f5-4d96-bfbb-7a72fa779759)

**Comment by CriticalFlaw** [comment]
Fixed in 804b8ea5554a3a105aa0a58c28525bd5d773983f. Please download the latest schema and re-test. You may need to clear your cache if there are issues. Thanks.
