### ISSUE TITLE
[flawhud] Issue with Mode Selection

### ISSUE THREAD

**Issue by J0sh-Man** [CriticalFlaw/TF2HUD.Editor#264]
There's a weird bug in the mode selection menu. When it's set to default, the options are misaligned, and with the old selection they're just non-existent. I have a 1900 x 1200 resolution and an 6:10 aspect ratio, but changing them didn't seem to fix the problem.

I don't know, nor if I checked, if this is an issue with TF2HudEditor or the Hud itself, but I'd like to see this fixed.

![20241114174726_1](https://github.com/user-attachments/assets/c031eed0-9c39-4cee-90b1-954418bb9a6a)
![20241114182155_1](https://github.com/user-attachments/assets/aeab6c16-3e1a-43d1-8f4b-17f9085a3b94)

**Comment by J0sh-Man** [comment]
Alright, thanks. I'll test it out and see if it works

**Comment by J0sh-Man** [comment]
Holy shit it worked!! Thanks man!

**Comment by CriticalFlaw** [comment]
Alternatively, you can try the preview build: https://github.com/CriticalFlaw/TF2HUD.Editor/releases/tag/3.4.2
