### ISSUE TITLE
Page controls not scaling to lower resolutions

### ISSUE THREAD

**Issue by MrBlockIsCool** [CriticalFlaw/TF2HUD.Editor#39]
![lol](https://user-images.githubusercontent.com/82632653/114973049-433c2000-9e9d-11eb-8d7e-f16f38038ae5.png)

Pls Help

**Comment by CriticalFlaw** [comment]
Can you try maximizing the app window please? rayshud has a lot of controls so the normal app window size cannot display them all.

**Comment by MrBlockIsCool** [comment]
It is maximized

**Comment by CriticalFlaw** [comment]
What is your screen resolution?

**Comment by MrBlockIsCool** [comment]
1366 x 788 (Ik its really small, hoping to get a new pc soon )

**Comment by micwoj92** [comment]
Activate Windows to unlock 1080p

**Comment by MrBlockIsCool** [comment]
k yhx it worked :D

**Comment by CriticalFlaw** [comment]
Implemented a scroll viewer in f5197bd578ab4691bc3d17ebcb797bdbabb0de93 so that the user can still view all the controls even in lower resolutions where all the controls may not fit inside the group box.
