### ISSUE TITLE
Hitmarkers not working unless the crosshair is enabled.

### ISSUE THREAD

**Issue by logitchy** [CriticalFlaw/TF2HUD.Editor#41]
idk if its because it only works with custom crosshairs but i dont think it works

**Comment by CriticalFlaw** [comment]
Which HUD is this for?

**Comment by CriticalFlaw** [comment]
You have to enable the crosshair for the hitmarker to display. If you want to see just the hitmarker and not the crosshair itself, then change the visibility of the crosshair to be transparent.

![image](https://user-images.githubusercontent.com/6818236/115156446-53e1c700-a052-11eb-91f1-5a2c4a195d4c.png)

**Comment by CriticalFlaw** [comment]
Updated the wording for the crosshair option to be less confusing.
