### ISSUE TITLE
Enabled folder was not created for a file-based customization.

### ISSUE THREAD

**Issue by Silexos** [CriticalFlaw/TF2HUD.Editor#58]
I wanted to experiment with the new scoreboard function and noticed a few areas where the text is larger in size where it probably shouldn't be. For an easy to look at list rather than looking back and forth, the areas I found were:

-The backpack's stats page's "next tip/reset stats" buttons
-In-game voice commands
-Player name when talking in game
-Engineer's build/destruction PDAs
-The scoreboard itself (though this seems to be a larger issue of the scoreboard not entering full screen mode)

Additionally thank you for the help/feedback on previous issues and apologies if these reports are at all bugging you. 

![20210601010312_1](https://user-images.githubusercontent.com/85089160/120289546-44bb7f00-c276-11eb-83bc-b7de697d2b91.jpg)
![20210601010454_1](https://user-images.githubusercontent.com/85089160/120289637-5bfa6c80-c276-11eb-8049-cdd8702f8680.jpg)
![20210601010710_1](https://user-images.githubusercontent.com/85089160/120289642-5dc43000-c276-11eb-897d-55268243f163.jpg)
![20210601010715_1](https://user-images.githubusercontent.com/85089160/120289646-5e5cc680-c276-11eb-9d42-6bd51ae6a7ca.jpg)

**Comment by Silexos** [comment]
No problem! I'm finding that looking for these small bugs is enjoyable. I'll let you know if I ever find anything else and thanks for the support!

**Comment by CriticalFlaw** [comment]
Fixed in 14c49172204e08b312a8e5efadbbd3e4361b1b78 and will be included in the coming version 2.2 release.
