### ISSUE TITLE
Broken Spectate

### ISSUE THREAD

**Issue by kapootis** [CriticalFlaw/TF2HUD.Editor#59]
When you die and spectate a teammate, its just all grey with broken text on the top

I do not know if its on all the huds, buts its on the default hud.

**Comment by CriticalFlaw** [comment]
Could you please reinstall the stock hud using the editor's reinstall option and try again, please?

**Comment by cooolbros** [comment]
This issue can be fixed by adding a resource/ui/spectator.res to https://github.com/CriticalFlaw/TF2HUD.Plus

**Comment by CriticalFlaw** [comment]
@kapootis Could you verify that reinstalling the hud fixes the problem?

**Comment by CriticalFlaw** [comment]
Closing due to lack of response from the reporting user. This issue is likely fixed as of f93974ed965009478cb3d7bcdf0f95cece2c48c3
