### ISSUE TITLE
Support for HUDs without customizations

### ISSUE THREAD

**Issue by CriticalFlaw** [CriticalFlaw/TF2HUD.Editor#61]
There should be an efficient way of implementing multiple HUDs into the editor. This should be done through a json list containing multiple huds without specific customization options, only name and download link.

Not all of these will be able to make use of the default schema (#63) so as the bare minimum the user should be able to download, install and uninstall these HUDs.

```
[
      {
        "Name": "hexhud",
        "Author": "Hypnotize",
        "Download": "https://github.com/Hypnootize/hexhud/archive/refs/heads/master.zip"
      },
      {
        "Name": "ahud",
        "Author": "n0kk",
        "Download": "https://github.com/n0kk/ahud/archive/refs/heads/master.zip"
      },
      ...
]
```

**Comment by WizardEngineer** [comment]
Couldn't you create code that could take the URL of the specific hud that will automatically download it straight to the custom folder while unpacking it from the `.zip`? Something similar to a `.bat` file that I made for pazer's version of ahud. I'm just unsure how you would be able to hook C# to work in a similar fashion to bat file but in C# (or Json as mentioned before)

**Comment by CriticalFlaw** [comment]
Implemented in https://github.com/CriticalFlaw/TF2HUD.Editor/commit/4032c3dfbbe7d163131db0e4e8fbce71a443a257. HUDs loaded from `shared.json` will display basic information and only give the option to install, reinstall or uninstall.

![image](https://user-images.githubusercontent.com/6818236/128283920-dd1402ea-027d-417a-998a-1a7c50006a70.png)
