### ISSUE TITLE
Text missing from hypnotize-hud in many places

### ISSUE THREAD

**Issue by Yolodude25** [CriticalFlaw/TF2HUD.Editor#69]
I was just trying out the new hud, and there is text missing in some hover areas, the scoreboard, and the kill feed. Do I have to install a certain font or something?
![text hover 1](https://i.imgur.com/Ic0QbLC.png)
![text hover 1](https://i.imgur.com/a3bPkV3.png)
![killfeed](https://i.imgur.com/Y0eLa9W.png)
![scoreboard](https://i.imgur.com/4mkdwpB.png)
the blu team has 16 players who i all dominated, and neither the usernames or domination icons show up.

**Comment by CriticalFlaw** [comment]
I think this is streamer Mode being erroneously enabled. Could you change the checkbox for that option, apply settings and see if that fixes it?

**Comment by Yolodude25** [comment]
Interesting, turning streamer mode on fixed all of that. I assume this is a bug with the checkbox state being the opposite of what setting is actually enabled.

**Comment by Yolodude25** [comment]
Sorry, update, it fixed the killfeed and the scoreboard, however the blank hovers in the menu are still present.

**Comment by CriticalFlaw** [comment]
Did you restart the game? Some changes are only applied after the game has been restarted.

**Comment by CriticalFlaw** [comment]
Fixed it in 7b52785e4f1e28a213d35c47b7a86da81eb5f8a9. You can download the fixed schema by clicking the refresh button near the bottom of the screen (same row as the media links and documentation buttons).

**Comment by Yolodude25** [comment]
after restarting, it fixed the hovers as well. When I try to update the schema it says there are no new schema updates available.
![image](https://user-images.githubusercontent.com/41439633/123654427-0fb23600-d7fc-11eb-9f12-94b8c05051d6.png)

**Comment by CriticalFlaw** [comment]
I think the updater does not detect enough of a change to trigger since change was so small. You can brute force an update by going to your HUD Editor directory, open `JSON` and delete `hypnotize-hud.json`. Next time you open the editor, it should download the latest copy.

**Comment by CriticalFlaw** [comment]
Fixed in 7b52785e4f1e28a213d35c47b7a86da81eb5f8a9. Users who have the same problem will need to refresh the HUD schemas.
