### ISSUE TITLE
Improve wording for the custom background feature.

### ISSUE THREAD

**Issue by transbimbozone** [CriticalFlaw/TF2HUD.Editor#70]
[ For Flawhud specifically ]

In order to restore the original background image you need to reinstall the hud in it's entirety. If reinstalling is by design, I think adding a question mark tab similar to "Health Style" specifying that would help.
![sdaadasda](https://user-images.githubusercontent.com/73834086/124045829-5f902900-d9c5-11eb-849b-00546c69eaa7.png)

**Comment by CriticalFlaw** [comment]
Does pressing the Reset button next to the Custom Background's Browse button then clicking Apply Changes not reset to the default background?

**Comment by transbimbozone** [comment]
Just checked to make sure it wasn't a fluke. That does happen when you have changed your background once, but if you've changed it more than once without resetting it it will instead use the last background before the newest one.
Like ( default -> background 1 -> background 2 -> reset -> background 1 )

**Comment by CriticalFlaw** [comment]
Added in 9e35cfc6e9e3216753efb91a59e70ed0d7917403. There is now a warning message when selecting a new background to tell the user that to go back to the default background, they will have to reinstall the HUD.
