### ISSUE TITLE
Persistent crosshair selection

### ISSUE THREAD

**Issue by vidhanio** [CriticalFlaw/TF2HUD.Editor#75]
It would be beneficial to be able to keep the same crosshair settings (maybe add a lock option or something), as when switching HUDs I think the majority of people keep the same crosshair. It also seems that each HUD uses similar crosshair options, so I think this may be possible.

**Comment by CriticalFlaw** [comment]
Implemented in 8321e4c45c63a1f6ee21084556011bd12b4d648b and 0a5e58f3e20131be63f269767687e39b16c33438.

The feature, which will be enabled via a toggle in the options menu - will remember the crosshair toggle, size, style and primary colors between HUDs that use the same features.
