### ISSUE TITLE
Rayshud Missing Alert Button

### ISSUE THREAD

**Issue by BoltyDawg** [CriticalFlaw/TF2HUD.Editor#80]
In the main menu and in game pause menu, there is no way to see your pending alerts. 

When booting up the game with a pending alert, I hear the notification sound notifying me of the pending alert (new items) however there's no actual button that I can interact with to open the alerts. 

For context, I used to use the old rayshud installer and the issue only came up when switching to using HUDEditor. I tried out other huds in the editor and none had the same problem. I am also using mastercomfig if that's at all relevant. 
I have not tried replicating this on a clean install of the game yet so it is possible this could be an error on my end. Please let me know if you believe that to be the case.
I also looked through my console log on bootup and didn't see anything that seemed relevant. However I can still provide that log file if needed. 

Proof of having a pending alert:
![InkedTeam Fortress 2 Screenshot 2021 07 27 - 17 12 26 05_LI](https://user-images.githubusercontent.com/36057500/127228409-25201f8c-4a22-4cbd-bf9f-d1dc98a61284.jpg)

What my main menu looks like:
![Team Fortress 2 Screenshot 2021 07 27 - 17 12 17 77](https://user-images.githubusercontent.com/36057500/127228433-3774108d-4b78-4b1b-b501-43aa30b733f1.png)

What my pause menu looks like:
![Team Fortress 2 Screenshot 2021 07 27 - 17 11 54 92](https://user-images.githubusercontent.com/36057500/127228458-28aae0bd-24ce-4538-89b8-bc0f2573bb39.png)

**Comment by BoltyDawg** [comment]
Forgot to mention this but I am using the latest release, version 2.2 and my schemas are up to date

**Comment by CriticalFlaw** [comment]
This isn't related to the editor and is instead an issue with rayshud itself. I moved the notification button and panel to be above the buttons on the right hand side of the screen for both modern and classic main menu styles. This should resolve the issue. Thanks!

https://github.com/raysfire/rayshud/commit/f93c2fed5bc1fe506cada968cbe205372b939810
