### ISSUE TITLE
scoreboard no work and kill feed no work

### ISSUE THREAD

**Issue by Bruhnin06** [CriticalFlaw/TF2HUD.Editor#82]
problem: ![20210803121014_1](https://user-images.githubusercontent.com/86055851/127961310-b4346104-b421-48e9-bea3-a0396aa46b39.jpg)

settings: 
![image](https://user-images.githubusercontent.com/86055851/127961366-08259304-1b99-4af9-8c43-9b5695d733c1.png)

scoreboard and kill feed no work

**Comment by Bruhnin06** [comment]
nvm im just dumb

**Comment by CriticalFlaw** [comment]
> nvm im just dumb

closing because user is dumb
