### ISSUE TITLE
Crash occurs when clicking GitHub, Huds.tf, Discord, and Steam buttons

### ISSUE THREAD

**Issue by theaswanson** [CriticalFlaw/TF2HUD.Editor#88]
**Describe the issue**
Depending on the current state of the app, a crash can occur when clicking one of the social buttons.

Looking at the code, some simple null checking would fix the issue. I can make a PR for this if desired!

**Steps to reproduce**
Steps to reproduce the issue:
1. Open the app
2. Click on GitHub, Huds.tf, Discord, or Steam

or

1. Open the app
2. Select a HUD (7HUD)
3. Click Customize
4. Click Switch HUDs
5. Click on GitHub, Huds.tf, Discord, or Steam

Expected behavior: the buttons are disabled since a HUD is not selected. Alternatively, a message pops up saying a HUD is not selected
Actual behavior: app crashes

**Desktop (please complete the following information):**
 - OS: Windows 10, x64
 - App Version: 2.3
 - Selected HUD: none

**Comment by CriticalFlaw** [comment]
That's a good catch. This doesn't happen when you highlight a HUD from the main menu but does when the screen main menu changes to its default state. Feel free to open a PR for it, seems straightforward enough.

**Comment by CriticalFlaw** [comment]
Fixed in ca196ffd97377ac6b4e682891fe686ad34f02285
