### ISSUE TITLE
Editor is flagged as virus by multiple AVs

### ISSUE THREAD

**Issue by CriticalFlaw** [CriticalFlaw/TF2HUD.Editor#90]
Multiple antiviruses are reporting version 2.3 of the editor as a virus. This is a false positive.

**Comment by CriticalFlaw** [comment]
Fixed in 93e2e7fbe21ee3c617259bdd9936f48b93eeb8da

**Comment by flamedestroyer1022** [comment]
its still seen as a virus on window's defender
