### ISSUE TITLE
tf/custom folder is deleted if HudSelection is null

### ISSUE THREAD

**Issue by Alessi1000** [CriticalFlaw/TF2HUD.Editor#92]
When I uninstalled SunsetHud my entire custom folder was deleted. Also before that, the hud just did not work

Steps to reproduce the issue:
I don't know

 - OS: Windows 10, x64]
 - App Version: [e.g. 2.3]
 - Selected HUD: [e.g. SunsetHud]

**Comment by Alessi1000** [comment]
also sunsethud doesn't work at all 
![image](https://user-images.githubusercontent.com/47134801/132120408-2600b41b-0211-4edb-9f27-b4ff4204bfd4.png)

**Comment by cooolbros** [comment]
Thank you for reporting this issue.

Looks like Sunset HUD is not being installed correctly because the zip file for contains a sunsetlight HUD and a sunsetdark HUD. Your custom folder being deleted is possibly caused the the selected HUD being "" (due to the HUD not downloading correctly?).

**Comment by CriticalFlaw** [comment]
I think we should pull Sunset HUD from the list until this can be resolved.

**Comment by getchoo** [comment]
No clue how to fix Sunset HUD, but I think I figured out how to stop the editor from deleting the entire custom folder in #94.

**Comment by cooolbros** [comment]
I'm not entirely sure what situation causes this to occur, but it has been fixed in c837de3174dedb302083b20aeee22fc5c4767b1b and will be released as part of the next update (2.4)
