### ISSUE TITLE
Localization Update (French, Russian)

### ISSUE THREAD

**Issue by CriticalFlaw** [CriticalFlaw/TF2HUD.Editor#93]
Below English text needs to be localized. 

| ID  | English | French  | Russian |
| ------------- | ------------- | ------------- | ------------- |
| info_add_hud | Are you sure you want to add a folder to the list of shared HUDs? This will add the folder locally but will not upload the HUD to TF2HUD.Editor's online database.  | :white_check_mark: | :white_check_mark: |
| info_background_override  | Setting a new background will override the current one. Use the "Reinstall" option to go revert to the default background. | :white_check_mark: | :white_check_mark: |
| tooltip_addhud | Add new HUD. | :white_check_mark: | :white_check_mark: |
| ui_author | Created by: {0} | :white_check_mark: | :white_check_mark: |
| ui_back | Back | :white_check_mark: | :white_check_mark: |
| ui_browse| Browse | :white_check_mark: | :white_check_mark: |
| ui_clear | Clear | :white_check_mark: | :white_check_mark: |
| ui_customize | Customize | :white_check_mark: | :white_check_mark: |
| ui_title| TF2 HUD Editor| :white_check_mark: | :white_check_mark: |
| ui_check_updates| Automatically check for updates| :white_check_mark: | :white_check_mark: |

**Comment by CriticalFlaw** [comment]
@tacokete, @Blueberryy are you available to translate the above for our next release, please?

**Comment by Blueberryy** [comment]
Alright, will do in a few.

**Comment by KayaDLX** [comment]
Just created a PR for the french localization #103

**Comment by CriticalFlaw** [comment]
All remaining English text has been translated. Thank you @Blueberryy and @KayaDLX
