### ISSUE TITLE
The editor wont shut up about requiring .NET...when i already have it.

### ISSUE THREAD

**Issue by JXTLGithub** [CriticalFlaw/TF2HUD.Editor#97]
### The editor just flat out refuses to open for me.
**It just keeps making a pop-up saying that I need .NET**, even after I installed the correct variation.
And I already tried restarting, and that didn't work either.

**Comment by CriticalFlaw** [comment]
Which variant did you install exactly?

**Comment by JXTLGithub** [comment]
> Which variant did you install exactly?

I installed the Desktop variation, which is what the website (or you) said.

**Comment by CriticalFlaw** [comment]
And was it x86 or x64 bit?

**Comment by CriticalFlaw** [comment]
Closing due to lack of response. The user likely installed an incorrect version of the .NET Core Runtime.
